import type { Metadata } from "next";
import Link from "next/link";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "What information BioClerk collects, why, how long we keep it, and what control you have over it.",
};

export default function PrivacyPage() {
  return (
    <>
      <SiteHeader variant="solid" />
      <main className="flex-1 bg-background">
        <div className="border-b border-border bg-surface">
          <div className="mx-auto w-full max-w-3xl px-5 py-12 sm:px-8 sm:py-16">
            <p className="text-sm font-semibold text-brand-deep">Legal</p>
            <h1 className="mt-2 text-4xl font-bold tracking-tight text-foreground">
              BioClerk Privacy Policy
            </h1>
            <dl className="mt-6 grid gap-3 text-sm text-muted sm:grid-cols-3">
              <div>
                <dt className="font-semibold text-foreground">Status</dt>
                <dd>DRAFT</dd>
              </div>
              <div>
                <dt className="font-semibold text-foreground">Version</dt>
                <dd>0.1</dd>
              </div>
              <div>
                <dt className="font-semibold text-foreground">Applies to</dt>
                <dd>BioClerk desktop app</dd>
              </div>
            </dl>
          </div>
        </div>

        <article className="legal-prose mx-auto w-full max-w-3xl px-5 py-12 sm:px-8 sm:py-16">
          <p>
            This Privacy Policy explains what information BioClerk collects,
            why, and what control you have over it. It&apos;s a separate
            document from our{" "}
            <Link href="/terms">Terms of Use</Link> because it covers different
            grounds in more detail: the specific categories of data involved,
            who we share them with, how long we keep them, and your rights.
          </p>

          <div className="legal-callout">
            <strong>The short version, if you read nothing else:</strong> by
            default, BioClerk never sends your dictation anywhere. Everything
            below describes the narrow set of things that are genuinely
            necessary to sell and license the software, plus one feature you
            have to turn on yourself before any dictation content leaves your
            device.
          </div>

          <h2 id="what-this-covers">What This Covers</h2>
          <p>
            This policy covers information collected through the BioClerk
            desktop application and the backend services it talks to (license
            activation, purchases, and the optional model-improvement upload).
            It does not cover the content of what your patients tell you — see{" "}
            <a href="#patient-information">Patient Information</a> below for
            why that&apos;s handled differently.
          </p>

          <h2 id="what-we-collect">What We Collect</h2>

          <h3>Information you give us directly</h3>
          <p>
            <strong className="text-foreground">Email address</strong> —
            collected when you buy a license, so we can send your purchase code
            and receipt, and reach you for support.
          </p>

          <h3>Information generated by the app</h3>
          <p>
            <strong className="text-foreground">A device fingerprint</strong> —
            a one-way cryptographic hash of a few hardware identifiers, plus a
            random ID the app generates for itself, both hashed before they
            ever leave your device. This exists purely to bind a license to the
            device it was activated on and prevent sharing a single purchase
            across unlimited machines; it cannot be reversed back into any
            identifying hardware details, and isn&apos;t personal information
            about you.
          </p>
          <p>
            <strong className="text-foreground">
              License and activation records
            </strong>{" "}
            — which license is active on which device fingerprint, and status
            checks used to detect a revoked or deactivated license.
          </p>

          <h3>Your dictation content</h3>
          <p>
            <strong className="text-foreground">By default:</strong> nothing
            leaves your device. Audio recordings and transcripts (the
            model&apos;s raw output, the formatted version, and anything you
            edit) are stored locally on your computer, encrypted at rest, and
            never transmitted anywhere.
          </p>
          <p>
            <strong className="text-foreground">
              Only if you turn on &quot;Share data with BioClerk&quot; in
              Settings (off by default):
            </strong>{" "}
            recordings and transcript text you produce afterward are uploaded,
            for the sole purpose described in{" "}
            <a href="#how-we-use-it">How We Use It</a> below. Turning this off
            again stops any further sharing going forward — it does not
            retroactively delete what was already shared; see{" "}
            <a href="#your-rights">Your Rights</a> for how to request that.
          </p>

          <h3>Payment information</h3>
          <p>
            We never see your card details. Payment is processed entirely by
            Paystack; BioClerk&apos;s own systems only receive a transaction
            reference and amount, never your card number or similar payment
            credentials.
          </p>

          <h2 id="how-we-use-it">How We Use It</h2>
          <table>
            <thead>
              <tr>
                <th>Category</th>
                <th>Purpose</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Email address</td>
                <td>
                  Deliver your purchase code, send receipts, respond to support
                  requests.
                </td>
              </tr>
              <tr>
                <td>Device fingerprint</td>
                <td>
                  Bind and verify your license to your device; detect abuse of
                  the trial/activation system.
                </td>
              </tr>
              <tr>
                <td>Opted-in recordings &amp; transcripts</td>
                <td>
                  Improve the accuracy of BioClerk&apos;s transcription model
                  over time. Never used for any other purpose, and never sold.
                </td>
              </tr>
            </tbody>
          </table>
          <p>
            We do not use any of this to build advertising profiles, and we do
            not sell personal information to anyone, under any circumstances.
          </p>

          <h2 id="who-we-share-it-with">Who We Share It With</h2>
          <p>
            <strong className="text-foreground">Paystack</strong> — processes
            your payment when you buy a license. Your email and transaction
            details pass through them; see Paystack&apos;s own privacy policy
            for how they handle payment data.
          </p>
          <p>
            <strong className="text-foreground">Google Cloud Storage</strong> —
            if (and only if) you&apos;ve opted in to sharing data, your audio
            recordings are stored in a Google Cloud Storage bucket we control,
            purely as a storage vendor.
          </p>
          <p>
            BioClerk&apos;s speech-to-text model (MedASR, made available by
            Google) runs entirely on your own device. Using it does not send
            any audio or transcript to Google. The only connection between your
            dictation and Google at all is the separate, opt-in storage step
            above, and even then Google Cloud Storage is being used purely as a
            storage vendor we chose, not as part of how the model itself works.
          </p>
          <p>
            We do not share your information with any other third party, and we
            do not share it for any party&apos;s own independent marketing
            purposes.
          </p>

          <h2 id="retention">Retention</h2>
          <p>
            Local data (recordings, transcripts, license state) stays on your
            device for as long as you keep BioClerk installed, until you delete
            it yourself or uninstall the app.
          </p>
          <p>
            Locally recorded audio is deleted from your device automatically
            once it&apos;s been synced (if you opted in), and in any case no
            later than around six months after it was recorded — whichever
            comes first.
          </p>
          <p>
            Opted-in data already uploaded is retained for as long as reasonably
            necessary to improve BioClerk&apos;s transcription model, after
            which it&apos;s deleted. If you&apos;d like previously-shared data
            deleted sooner, contact us (see{" "}
            <a href="#contact-us">Contact Us</a>) and we&apos;ll action the
            request.
          </p>
          <p>
            Purchase and license records are kept for as long as your license
            could reasonably need support, and as required to meet our own
            tax/accounting obligations.
          </p>

          <h2 id="security">Security</h2>
          <p>
            Recordings and transcripts stored locally are encrypted at rest on
            your device.
          </p>
          <p>
            Everything sent to our backend (activation, purchase, optional sync)
            travels over an encrypted HTTPS connection.
          </p>
          <p>
            No system is perfectly secure, and we can&apos;t guarantee absolute
            security — but we don&apos;t collect more than we need, specifically
            so there&apos;s less at risk if something ever did go wrong.
          </p>

          <h2 id="your-rights">Your Rights</h2>
          <ul>
            <li>
              <strong className="text-foreground">Turn sharing off</strong> at
              any time, from Settings — takes effect immediately for anything
              recorded afterward.
            </li>
            <li>
              <strong className="text-foreground">Ask what we have</strong> —
              request a copy of the personal information (email, purchase
              records, any data you&apos;ve opted to share) we hold about you.
            </li>
            <li>
              <strong className="text-foreground">Ask us to delete it</strong> —
              including data already uploaded under the opt-in sharing feature,
              subject to what we&apos;re legally required to keep (e.g. basic
              purchase records for tax purposes).
            </li>
            <li>
              <strong className="text-foreground">Correct it</strong> — if
              anything we hold about you (like your email) is wrong.
            </li>
          </ul>
          <p>
            To exercise any of these, contact us at the address below. We&apos;ll
            respond within a reasonable time.
          </p>

          <h2 id="patient-information">Patient Information</h2>
          <p>
            This policy covers information about you — the person using
            BioClerk. It does not cover the patient information contained within
            what you dictate. By default, that content never leaves your device
            at all, and even if you opt into sharing, you remain the one
            responsible for complying with whatever health-data privacy laws
            apply to your own practice and your patients — including obtaining
            any consent you&apos;re required to obtain before dictating
            identifiable patient information, and before opting that content
            into the sharing feature specifically. BioClerk is a tool you use;
            it doesn&apos;t make that judgment for you.
          </p>

          <h2 id="children">Children</h2>
          <p>
            BioClerk is a professional tool for clinicians and is not directed
            at, marketed to, or knowingly used to collect information from
            children.
          </p>

          <h2 id="international-transfers">International Transfers</h2>
          <p>
            Paystack and Google Cloud Storage may process or store information
            outside the country you&apos;re in. We only work with providers who
            maintain appropriate safeguards for the information they process on
            our behalf.
          </p>

          <h2 id="changes">Changes to This Policy</h2>
          <p>
            We may update this policy from time to time — for example, if we add
            a feature that changes what data is involved. We&apos;ll update the
            version shown at the top of this page when we do. Material changes
            affecting how previously-collected data is used will be communicated
            before they take effect.
          </p>

          <h2 id="contact-us">Contact Us</h2>
          <p>
            Questions, or a request about your data? Reach us at{" "}
            <a href="mailto:support.bioclerk@gmail.com">
              support.bioclerk@gmail.com
            </a>
            .
          </p>

          <p className="mt-12 text-sm">
            Also see our <Link href="/terms">Terms of Use</Link>.
          </p>
        </article>
      </main>
      <SiteFooter />
    </>
  );
}
